all:
	gcc -o test_queue test_queue.c queue.c
	gcc -o test_queue_codeblocks test_queue_codeblocks.c
	gcc -o test_stack test_stack.c stack.c
	gcc -o test_stack_codeblocks test_stack_codeblocks.c
	gcc -o meio_lista meio_lista.c list.c
	gcc -o meio_lista_codeblocks meio_lista_codeblocks.c
clean:
	rm test_queue test_queue_codeblocks test_stack test_stack_codeblocks meio_lista meio_lista_codeblocks 
