all:
	gcc -o back back.c list.c -lm
	gcc -o back-codeblocks back-codeblocks.c
	gcc -o circular circular.c list.c -lm
	gcc -o circular-codeblocks circular-codeblocks.c 
	gcc -o split split.c list.c -lm
	gcc -o split-codeblocks split-codeblocks.c
	gcc -o replicate replicate.c list.c -lm
	gcc -o crivo crivo.c list.c -lm
	gcc -o snake snake.c deque.c -lm
clean:
	rm back back-codeblocks circular circular-codeblocks split split-codeblocks replicate crivo snake
