all:
	gcc -o in in.c list.c -lm
	gcc -o in-codeblocks in-codeblocks.c
	gcc -o sum sum.c list.c -lm
	gcc -o sum-codeblocks sum-codeblocks.c
	gcc -o merge merge.c list.c -lm
	gcc -o merge-codeblocks merge-codeblocks.c
	gcc -o poly-sum poly-sum.c plist.c -lm
	gcc -o test-graph test-graph.c graph.c -lm
clean:
	rm in in-codeblocks sum sum-codeblocks merge merge-codeblocks poly-sum test-graph
